### PR TITLE
Update version to include recent fixes to the lib

### PR DESCRIPTION
**Pull request by altinselimi**

### CODE REVIEW

**Comment by xlcrr** [comment]
Thanks for updating the package

When I try to install `v2.1.2` I get an error 

```
Module not found: Error: Can't resolve 'kalendar-vue'
```

But it builds fine when I downgrade to `v2.1.1`.

Tried deleting node_modules too, no luck.

Wondering if anyone else has the same problem?

**Comment by altinselimi** [comment]
@xlcrr yeah I published without npm run build. Publishing packages on npm is more complicated than it should be. 2.1.3 should fix it. Released now. Im not sure why but the week navigator still shows wrong dates...

**Comment by xlcrr** [comment]
Screenshot 2022-08-03 at 11 38 48

v2.1.3 works for me now

**Comment by xlcrr** [comment]
So it worked for me locally, but when I pushed to staging we get

```
Failed to resolve async component: function KalendarWeekView() {
```

**Comment by altinselimi** [comment]
@xlcrr what does your `npm run build` output. Was it working before with 2.1.1 ?

**Comment by xlcrr** [comment]
After upgrading the package to 2.1.3, `npm run build` shows

```
> kalendar-vue@2.1.3 build
> cross-env NODE_ENV=production rollup --config build/rollup.config.js

loaded build/rollup.config.js with warnings
(!) Unused external imports
terser imported from external module 'rollup-plugin-terser' but never used

src/index.js → dist/...
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
created dist/ in 1.8s

src/index.js → dist/kalendar-vue.umd.js...
created dist/kalendar-vue.umd.js in 813ms
```

It works fine standalone without running `npm run build`

**Comment by altinselimi** [comment]
@xlcrr I mean the project that is failing on staging, the output is fine for kalendar itself.

**Comment by xlcrr** [comment]
@altinselimi our staging is serverless, I cannot ssh into it and update anything. It's working fine for me locally.

Getting this error in the logs on staging environment

```
[Vue warn]: Failed to resolve async component: function KalendarWeekView() {
      return __webpack_require__.e(/*! import() */ "node_modules_kalendar-vue_dist_kalendar-weekview-8e8cef43_js").then(__webpack_require__.bind(__webpack_require__, /*! ./kalendar-weekview-8e8cef43.js */ "./node_modules/kalendar-vue/dist/kalendar-weekview-8e8cef43.js"));
    }
Reason: ChunkLoadError: Loading chunk node_modules_kalendar-vue_dist_kalendar-weekview-8e8cef43_js failed.
(error: https://mysite.test/js/node_modules_kalendar-vue_dist_kalendar-weekview-8e8cef43_js.js)
```

**Comment by xlcrr** [comment]
I was able to fix this by deleting the compiled files in the `public/js` folder, reinstalling the package which produced new files, and then importing the new ones in the header

**Pull request merged**
